# Generated by Django 4.2.2 on 2023-06-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_lesson_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='update_date',
            new_name='updated_date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=263, null=True),
        ),
    ]
